[package]
name = "redis-alchemy"
version = "0.1.0"
authors = ["Shiwei Zhang <ylxdzsw@gmail.com>"]
edition = "2018"

[dependencies]
oh-my-rust = { path = "/home/ylxdzsw/fuck-projects/oh-my-rust" }
detached-bufreader = { path = "/home/ylxdzsw/fuck-projects/detached-bufreader" }